name: CI

on:
  push:
    branches: [ main, staging, trying ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install C libraries for tooling
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev

      - run: cargo build
      - run: cargo test

  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install C libraries for tooling
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev

      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
